### ISSUE TITLE
Delete Horizontal Whitespace command only operates on text currently in the viewport

### ISSUE THREAD

**Issue by akatakritos** [madskristensen/TrailingWhitespace#12]
When I run the Delete Horizontal Whitespace command, either through Edit -> Advanced or via the shortcut key, only the trailing whitespace currently visible on the screen is removed.

I notice this in VS2012 and VS2013 Professional. I tried disabling all other extensions and still could reproduce the issue.

Reproduce:
1. Create a new Console Application
2. Add some trailing whitespace around the Main method.
3. Create a bunch of blank lines until the Main method has scrolled off the top of the view port
4. Add some trailing whitespace to that last line in the file
5. (optional) save the document
6. Scrolll back to the top and execute Delete Horizontal Whitespace via the Menu or shortcut

**Result**: Only the trailing whitespace in the current view has been cleared: scroll to the bottom and see there is still some left.

**Expected**: All trailing whitespace in the document has been cleared

Looking at the code, I think the issue might be that `ITextBuffer` represents the text currently displayed in the view port.

I've never written an extension before, but would be willing to try and submit a PR for this if this turns out to be more than just an environmental issue with my PC or is actually desired behavior.

Thanks for your help!

**Comment by madskristensen** [comment]
Version 1.9 fixes the issue. It has just been released. Thanks for the bug report

**Comment by akatakritos** [comment]
Thanks, @madskristensen! Great extension!
