### ISSUE TITLE
Trailing whitespace marked red in Conditional Breakpoint Dialog

### ISSUE THREAD

**Issue by akatakritos** [madskristensen/TrailingWhitespace#17]
This is VS 2013 update 4, but I've seen it in 2012 as well.

The trailing whitespace color is applied inside the Breakpoint Condition dialog.

![whitespace-in-conditional-breakpoint](https://cloud.githubusercontent.com/assets/3689068/5893704/e1ad2472-a4b3-11e4-8375-d1bea00f320c.png)

**Comment by madskristensen** [comment]
I've tried to fix this but to no prevail. It appears that this particular input field identifies as a code document

**Comment by madskristensen** [comment]
This has just been fixed

**Comment by akatakritos** [comment]
Thanks @madskristensen!
