### ISSUE TITLE
Trailing whitespace marked red in XML comments

### ISSUE THREAD

**Issue by benmccallum** [madskristensen/TrailingWhitespace#18]
Sometimes when writing XML comments on classes/members I will use an empty line in long descriptions. In VS, hitting Enter gives you a new line with `/// ` (notice the trailing space). That trailing space gets highlighted red, but it's not a particularly bad case that needs highlighting.

I wonder if we can just ignore that scenario?

I'd say it should start going red after that initial space though.

Would be happy to put in a PR when I get a chance.

**Comment by madskristensen** [comment]
I don't think this extension should be opinionated about such specific scenarios. A trailing whitespace is neither good or bad, it just is and this extension shows it. For instance, in markdown files, 2 trailing spaces are useful for creating new lines.

**Comment by benmccallum** [comment]
Good point. We'd be opening a can of worms.

Only alternative solution I can think of is having a blacklist of regexs a user could add as ignores they want. Still violates yor point that this is a white space visualiser, plain and simple, take it literally. 

Nevermind :)
