### ISSUE TITLE
Automatically trim trailing whitespace on file save

### ISSUE THREAD

**Issue by drewnoakes** [madskristensen/TrailingWhitespace#19]
If this were possible, it'd make a great addition.

Optionally apply this only to lines which were modified since the last save.

**Comment by drewnoakes** [comment]
This is definitely more useful. However without #9, I'm not likely to use this plugin as it's very in-your-face when typing.

**Comment by madskristensen** [comment]
@drewnoakes Can you please help testing it out? Download here http://vsixgallery.com/extension/4c1a78e6-e7b8-4aa9-8812-4836e051ff6d/

**Comment by madskristensen** [comment]
I'm still tying to figure out how to fix #9

**Comment by drewnoakes** [comment]
For sure. Installing now...

**Comment by drewnoakes** [comment]
Trailing whitespace is successfully cleared upon save. Looks good to me. Thanks again

**Comment by drewnoakes** [comment]
This functionality does not appear to work with "Save All".

To reproduce, modify a file to add EOL whitespace. Choose Save All in VS (Ctrl+Shift+S, for me at least) and note the whitespace remains.

**Comment by madskristensen** [comment]
I've fixed the "Save all" issue as well as implemented delayed visualize #9. You can download the never new version (1.10.47)  from http://vsixgallery.com/extension/4c1a78e6-e7b8-4aa9-8812-4836e051ff6d/ momentarily

**Comment by drewnoakes** [comment]
That's fantastic news. I'll test it out later today.

**Comment by harriha** [comment]
What a perfect timing to get this feature in, just when I started fine-tuning my VS setup and started (once again) looking for a way to do this nicely.

While at it, I tested that 'Save all' feature, and unfortunately it doesn't seem to work for me with the 1.10.47 (Visual Studio 2013 Community, v 12.0.31101.00 Update 4). Trailing whitespace disappears from the currently active file, but not from others. However, maybe better to wait for more testing feedback from @drewnoakes before jumping into further conclusions here.

Apart from that, the feature seems to work fine for me as well, thanks a lot :+1:.

**Comment by drewnoakes** [comment]
Save All is improved in that it does actually process the focussed source file, but unsaved files in other tabs/panels do not have their whitespace trimmed as they are saved.

The delayed visualisation is absolutely perfect and makes this add in a great addition to VS. I'm going to get my whole team to install it on Monday.

**Comment by madskristensen** [comment]
Gotcha. I saw it only trims the whitespace of the currently focused file. I'll look into it

**Comment by harriha** [comment]
@madskristensen Seems that you released a new official version with this fix, cool, thanks. FYI, it seems that the release date for v2.0 in https://visualstudiogallery.msdn.microsoft.com/a204e29b-1778-4dae-affd-209bea658a59 is a bit off, probably worth fixing.
