### ISSUE TITLE
Allow all files in a folder to be ignored when removing whitespace.

### ISSUE THREAD

**Issue by fspafford** [madskristensen/TrailingWhitespace#22]
I would like the option to ignore certain folders when removing whitespace. 

We use some 3rd party source files, in a specific folder, and I would like to not alter the whitespace in these files.

Thanks for a nice tool.

Frank

**Comment by madskristensen** [comment]
The whitespace removal happens on save by default. Do you save 3rd party source files?

**Comment by fspafford** [comment]
Unfortunately we do, because we make a few custom changes.

**Comment by drewnoakes** [comment]
@fspafford a workaround is to switch to another document and execute _Save All_ (Ctrl+Shift+S on my PC). This saves the file in the non-focussed tab without stripping the whitespace from it.

**Comment by JohnTasler** [comment]
Actually, I think a better option would be to specify exclusion folders/sub-folders. For each exclusion, we could specify whether we want to hide trailing whitespace, as well as whether we want to remote trailing whitespace on Save.

When I open files in C++ CRT/STD libraries (such as those included with VS), it's just a bunch of noise to see the trailing whitespace in these files that I have no control of.

**Comment by madskristensen** [comment]
There is now an option to specify what folders to exclude.

@JohnTasler What is the folder name of the C++ libraries you mention? I can add that to the default ignore list

**Comment by fspafford** [comment]
Thank you Mads, for the option to exclude folders.

Regards,
Frank
 

    On Friday, February 5, 2016 3:26 PM, Mads Kristensen <notifications@github.com> wrote:
 

 There is now an option to specify what folders to exclude.@JohnTasler What is the folder name of the C++ libraries you mention? I can add that to the default ignore list—
