### ISSUE TITLE
Disable for <auto-generated> source files

### ISSUE THREAD

**Issue by drewnoakes** [madskristensen/TrailingWhitespace#23]
System.CodeDom generates files with loads of trailing whitespace.

The types could be identified via the `GeneratedCodeAttribute`, but I assume TrailingWhitespace works on text directly and is not aware of its meaning in any way.

Such CodeDom code starts with something like:

```csharp
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
```

A potentially simple approach here is just to disable highlighting of whitespace on files which have this comment, perhaps just testing whether the second line contains `\\ <auto-generated>`.

**Comment by JohnTasler** [comment]
+1

**Comment by madskristensen** [comment]
Please help verify the fix in the CI build found here http://vsixgallery.com/extension/4c1a78e6-e7b8-4aa9-8812-4836e051ff6d/
