### ISSUE TITLE
Option to enable only for files in the project heirarchy

### ISSUE THREAD

**Issue by drewnoakes** [madskristensen/TrailingWhitespace#24]
When navigating to library source code (eg the BCL) there's often tonnes of trailing whitespace. I don't need to see that, and it's distracting. These files aren't under my control either.

For example:

![image](https://cloud.githubusercontent.com/assets/350947/13981349/fdcc848e-f126-11e5-856d-2874d5ba7ab8.png)

Is it possible to detect that the file being viewed is not in the solution, and disable visualisation of trailing whitespace? I think this might make a good default, but I'd be happy to enable an option for this.

**Comment by madskristensen** [comment]
I think that you would want to visualize whitespace in misc files (files outside a project), but you don't want it on files that aren't yours to modify. Is that a correct assumption? 

Is there a way to identify files that are outside our control like in your case? For instance, are they marked as read-only or are they located in specific folders somewhere on disk?

**Comment by drewnoakes** [comment]
Apologies for not getting back to you sooner. Reading the commit, it seems that this does what I was after, so thanks very much!

Answering your question specifically, I'm happy to disable this extension for any non-solution files. However the specific case I show above is categorizable by file path. For example:

> C:\Users\Drew\AppData\Local\Symbols\src\source\.NET\4\DEVDIV_TFS\Dev10\Releases\RTMRel\ndp\clr\src\BCL\System\Reflection\AssemblyAttributes.cs\1305376\AssemblyAttributes.cs

Thanks again Mads.
