### ISSUE TITLE
Is "remove whitespace on save" supposed to work for build of a project?

### ISSUE THREAD

**Issue by RenniePet** [madskristensen/TrailingWhitespace#28]
Is "remove whitespace on save" supposed to work for the implicit save that occurs when you build a project, or only for explicit saves of the source file(s)?

For me it's working when I do an explicit File - Save, but not when the file gets saved because I build the project.

Thanks for this extension, by the way.

**Comment by madskristensen** [comment]
No, it is only supposed to work when you explicitly saves a source file

**Comment by RenniePet** [comment]
OK, thanks for your reply.

Do you maybe have a suggestion about how to change it to also work when the file is saved implicitly for doing a build?

**Comment by madskristensen** [comment]
I guess you'd have to loop through all open files and call the remove whitespace command on each of them
