### ISSUE TITLE
Option to remove some trailing whitespace but not all

### ISSUE THREAD

**Issue by RenniePet** [madskristensen/TrailingWhitespace#29]
I actually like to have a single blank at the end of a comment line when the comment is continued on the next line. Also like having a single blank at the end of a line when it is a C# statement that has been broken over several lines. 

For example:

         // Find the ActionMethodInfo for the secondary action method. (Alternatively this method#
         //  could require that the caller specified it explicitly, but this technique is a bit#
         //  easier to implement.)
         ActionMethodInfo<TObject> actionMethodInfo =#
                                         objectTableEntry.FindSecondaryActionMethod(enclosingClass);

where # marks the places that I prefer to have a single trailing blank.

I've added code to your extension to do that, i.e., remove most trailing whitespace but keep a single blank in these particular situations. Are you perhaps interested in a pull request? With a bit of fiddling this could be a three-way option: Remove whitespace on save? No, All or Syntax-based.

**Comment by madskristensen** [comment]
I think that is a very specific requirement that I doubt other people have. I think supporting it would do nothing more than add complexity to users that doesn't need/want the feature
