### ISSUE TITLE
Extension repeatedly set as disabled

### ISSUE THREAD

**Issue by drewnoakes** [madskristensen/TrailingWhitespace#30]
Quite regularly, this extension becomes disabled. I have to manually enable it and restart VS.

This doesn't happen with any other installed extensions.

Are there some log files I can look in to debug this further?

- Visual Studio 2015
- Extension 2.4.72

**Comment by madskristensen** [comment]
I get this issue now and again reported to some of my extensions. Unfortunately it is not a bug in the extensions themselves, but in the Visual Studio extension management logic. The only thing I've found to work is to clear the MEF cache. Try this https://visualstudiogallery.msdn.microsoft.com/22b94661-70c7-4a93-9ca3-8b6dd45f47cd

**Comment by drewnoakes** [comment]
Actually this didn't seem to stick, and now I can't make the TWV extension work at all. Is there a very precise series of steps one needs to follow? I've tried several combinations of things but nothing makes the extension load. Every time I check, it's disabled.

Perhaps you know something else I could try manually.

**Comment by drewnoakes** [comment]
Turns out that somehow the extension was installed twice and that was causing it to be disabled at startup. Uninstalling twice (restarting each time) then reinstalling fixed the problem.

This tool cleans up duplicate extensions. Seems to have worked for me: https://github.com/remcoros/DuplicateExtensionFinder
