### ISSUE TITLE
Project tagline understates awesomeness

### ISSUE THREAD

**Issue by drewnoakes** [madskristensen/TrailingWhitespace#31]
![image](https://cloud.githubusercontent.com/assets/350947/15887189/c4e5f51a-2d58-11e6-8a23-18cee757d041.png)

This text also appears in Google search results:

![image](https://cloud.githubusercontent.com/assets/350947/15887207/de331836-2d58-11e6-94b6-1c8af7dbdc16.png)

There's a whole extra use case that isn't made mention of, namely automatically cleaning up whitespace. That might actually be what a prospective user is primarily looking for.

**Comment by madskristensen** [comment]
Good idea. I've updated the text. Thanks for the suggestion

**Comment by drewnoakes** [comment]
Greater thanks are due for the extension.
