### ISSUE TITLE
Error in ActivityLog.xml

### ISSUE THREAD

**Issue by PhilBarila** [madskristensen/TrailingWhitespace#32]
### Installed product versions
- Visual Studio: 2015 Enterprise Update 2
- This extension: 2.4.73

### Description
As the title, there is an error in ActivityLog.xml.  After the error happens, it's very likely that VS will crash in the near future, usually with the merge tool open resolving conflicts.

### Steps to recreate
1. Seems to be related to C++ source files, because I see it much more often when I'm working with them. Not sure I've seen it without at least opening a C++ source, but I can't completely attest to that.
2. Seems more likely to happen when doing conflict resolution while merging between branches. 

### Current behavior
Here's the log fragment from ActivityLog:
1139  Begin package load [Visual C++ Language Manager Package] {8C2EA640-ABC1-11D0-9D62-00C04FD9DFD9}  VisualStudio 2016/05/26 14:54:55.051 

1140  End package load [Visual C++ Language Manager Package] {8C2EA640-ABC1-11D0-9D62-00C04FD9DFD9}  VisualStudio 2016/05/26 14:54:55.107 

1141 ERROR System.NullReferenceException: Object reference not set to an instance of an object. at TrailingWhitespace.FileHelpers.IsFileSupported(ITextBuffer buffer) in C:\projects\trailingwhitespace\src\Helpers\FileHelpers.cs:line 27 at TrailingWhitespace.TrailingClassifierProvider.GetClassifier(ITextBuffer textBuffer) in C:\projects\trailingwhitespace\src\Classifier\ClassifierProvider.cs:line 19 at Microsoft.VisualStudio.Text.Classification.Implementation.ClassifierTaggerProvider.<>c__DisplayClass12_0`1.<CreateTagger>b__0(IClassifierProvider provider) at Microsoft.VisualStudio.Text.Utilities.GuardedOperations.InvokeEligibleFactories[TExtensionInstance,TExtensionFactory,TMetadataView](IEnumerable`1 lazyFactories, Func`2 getter, IContentType dataContentType, IContentTypeRegistryService contentTypeRegistryService, Object errorSource)   Editor or Editor Extension 2016/05/26 14:54:56.002

### Expected behavior
Shouldn't produce the error, VS shouldn't crash.  Since the crashes only seem to happen after I get the popup about the error in ActivityLog.xml, it seems a reasonable conclusion that it's this extension that is destabilizing VS.

**Comment by madskristensen** [comment]
Fixed

**Comment by PhilBarila** [comment]
Great, thanks!
