### ISSUE TITLE
Trailing whitespace should not be removed inside multiline verbatim strings (C#)

### ISSUE THREAD

**Issue by mbischoff** [madskristensen/TrailingWhitespace#33]
### Installed product versions
- Visual Studio: 2015 Enterprise
- This extension: 2.4.74

### Description
The extension removes trailing whitespace inside multiline verbatim string, e.g:

```
var s = @"multiline      
text with spaces         
here:     ";
```

### Steps to recreate
1. add a multiline, verbatim string to a C# file
2. save file

### Current behavior
Trailing whitespace is removed

### Expected behavior
verbatim strings shouldn't be touched by the extension

**Comment by madskristensen** [comment]
Thanks for the fix
