### ISSUE TITLE
Support for Visual Studio Express 2015

### ISSUE THREAD

**Issue by jaafreitas** [madskristensen/TrailingWhitespace#36]
### Installed product versions
- Visual Studio: [Express 2015 for Web/Desktop]
- This extension: [example 1.1.21]

### Description
It's impossible to install this extension in the Visual Studio Express family. It seems that the only limitation is the list of supported products in the installer, which is limited to Visual Studio Pro family.

### Steps to recreate
1. Install Visual Studio 2015 Express for Web/Desktop
2. Try to install the Trailing Whitespace extesion

### Current behavior
VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products. 
Supported Products : 
- Microsoft.VisualStudio.Pro Version : [12.0, 14.0, 15.0]

### Expected behavior
The extension should install just fine in any Visual Studio 2015 family product.

**Comment by madskristensen** [comment]
Unfortunately, VS Express doesn't support 3rd party extensions. Community does and the **Microsoft.VisualStudio.Pro** moniker includes support for Community

**Comment by jaafreitas** [comment]
My bad, @madskristensen. I misunderstood the difference between the Community and Express. Thanks for your time.
