### ISSUE TITLE
Add .designer.cs to ignored patterns by default

### ISSUE THREAD

**Issue by jnm2** [madskristensen/TrailingWhitespace#47]
The Windows Forms designer generates a ton of comments where the first and last line have a single trailing space:

```cs
// 
// discardButton
// 
```

Any time you make a change manually in that file, for example to delete an event subscription line which showed up in the error list when you deleted the handler method, all these spaces get stripped. This makes the diff difficult to actually read in pull requests.

There's a perfect feature for this, Tools > Options > Environment > Trailing Whitespace > Ignore pattern. Would this make sense as a good default? That way I don't have to remember this across several VS installations and machines and for other developers on the team.

**Comment by maettu-this** [comment]
Yes, please! Actually, not only designer files `.Designer.cs`, but also `.resx` and potentially several other Visual Studio Designer related patterns. After all, [TrailingWhitespace](https://github.com/madskristensen/TrailingWhitespace/) is a Visual Studio plugin, so I guess it should be prepared to deal with the aspects of Visual Studio ;-)

**Comment by jnm2** [comment]
It looks like lines to change are:

https://github.com/madskristensen/TrailingWhitespace/blob/326d8678e137a94821600e602a4f200438f51680/src/Options.cs#L13

https://github.com/madskristensen/TrailingWhitespace/blob/326d8678e137a94821600e602a4f200438f51680/src/Options.cs#L27

@madskristensen Is there anything more to dealing with options than this?

**Comment by yannduran** [comment]
Wouldn't adding `.designer.` to the ignore pattern cause them to be ignored? Just like there's already `.min.`.

**Comment by jnm2** [comment]
PR is up: https://github.com/madskristensen/TrailingWhitespace/pull/53

**Comment by yannduran** [comment]
That's what I should have done, isn't it Joseph? lol
