### ISSUE TITLE
TrailingWhitespace uses synchronous auto-load

### ISSUE THREAD

**Issue by jakubsuchybio** [madskristensen/TrailingWhitespace#51]
### Installed product versions
- Visual Studio: [2019 Enterprise Preview 1]
- This extension: [2.5.90]

### Description
When I start VS2019 Preview 1 I get this type of error:
```Visual Studio has detected one or more extensions that are at risk of not functioning in a future VS update. Click 'Learn Mode' for next steps.```
After I click ```Learn More``` I get here:
https://blogs.msdn.microsoft.com/visualstudio/2018/05/16/improving-the-responsiveness-of-critical-scenarios-by-updating-auto-load-behavior-for-extensions/
After I do the steps in this link, I found that TrailingWhitespace extension gives me this message in ActivityLog.xml:
```
  <entry>
    <record>712</record>
    <time>2018/12/06 06:36:26.456</time>
    <type>Warning</type>
    <source>SyncAutoLoadedExtensions</source>
    <description>Extension &apos;Trailing Whitespace Visualizer&apos; uses the &apos;synchronous auto-load&apos; feature of Visual Studio. This feature will no longer be supported in a future Visual Studio 2019 update, at which point this extension will not work. Please contact the extension vendor to get an update. (UI Context: {adfc4e63-0397-11d1-9f4e-00a0c911004f} Package Guid: {043286da-34d9-44a7-93eb-16a775cfcf61})</description>
  </entry>
```
### Steps to recreate
1. Install VS2019 Preview 1
2. Install Trailing Whitespace Extension
3. Open VS2019 Preview 1 (skip solution selection dialog to full VS IDE)
4. See the yellow warning message on top

### Current behavior
Yellow warning message on top

### Expected behavior
No warning message

**Comment by jnm2** [comment]
Came to say the same.

![image](https://user-images.githubusercontent.com/8040367/49592551-68b8d680-f93f-11e8-9d7a-618ae78e9ddb.png)

**Comment by madskristensen** [comment]
This should now be fixed. Can you please help verify it works by installing the latest CI build? http://vsixgallery.com/extension/4c1a78e6-e7b8-4aa9-8812-4836e051ff6d/

**Comment by jnm2** [comment]
@madskristensen The CI build appears to work fine! No warnings in VS 2019 Preview 1.

**Comment by madskristensen** [comment]
I just uploaded the new release. Thanks @jnm2 for testing
